version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/app'
      - '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5
    labels:
      - 'electron'
    allow:
      - dependency-name: 'electron'
